# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'iosMail' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosMail

  pod 'CLTypingLabel'
  #pod 'Firebase/Auth'
  #pod 'Firebase/Firestore'
  pod "IQKeyboardManager"
	pod 'GoogleAPIClientForREST'
	#pod 'GoogleAPIClient/Gmail'
	pod "GTMSessionFetcher"
	pod 'GoogleSignIn'
end
